# Generated by Django 4.1.5 on 2023-01-03 23:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Filament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PLA", "PLA"),
                            ("ABS", "ABS"),
                            ("PETG", "PETG"),
                            ("ASA", "ASA"),
                            ("HIPS", "HIPS"),
                            ("Nylon", "Nylon"),
                            ("PC", "PC"),
                            ("PP", "PP"),
                            ("TPU", "TPU"),
                            ("Special", "Special"),
                        ],
                        max_length=100,
                    ),
                ),
                ("material", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("quantity_in_kg", models.DecimalField(decimal_places=1, max_digits=3)),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filaments.manufacturer",
                    ),
                ),
            ],
        ),
    ]
